// examples/react-ui/src/components/FormInput/FormInput.tsx
import React from 'react';

interface FormInputProps {
  label: string;
  value: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onInput?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  disabled?: boolean;
  placeholder?: string;
  rightLabel?: string | (() => string);
  type?: 'text' | 'number' | 'email' | 'password';
  className?: string;
  inputClassName?: string;
  labelClassName?: string;
}

export const FormInput: React.FC<FormInputProps> = ({ label, value, onChange, onInput, disabled = false, placeholder = '', rightLabel, type = 'text', className = '', inputClassName = '', labelClassName = '', }) => {
  return (
    <div className={`${className}`}>
      <label className={`form-label flex flex-row justify-between ${labelClassName}`}>
        <span>{label}</span>
        {rightLabel && (
          <span>
            {typeof rightLabel === 'function' ? rightLabel() : rightLabel}
          </span>
        )}
      </label>
      <input
        type={type}
        value={value}
        onChange={onChange}
        onInput={onInput}
        disabled={disabled}
        placeholder={placeholder}
        className={`form-input ${inputClassName}`}
      />
    </div>
  );
};

// examples/vue-ui/src/components/FormInput.vue
<template>
  <div :class="className">
    <label :class="['form-label flex flex-row justify-between', labelClassName]">
      <span>{{ label }}</span>
      <span v-if="rightLabel">
        <span v-if="typeof rightLabel === 'function'">{{ rightLabel() }}</span>
        <span v-else>{{ rightLabel }}</span>
      </span>
    </label>

    <input
      :type="type"
      :value="value"
      @input="handleInput"
      :disabled="disabled"
      :placeholder="placeholder"
      :class="['form-input', inputClassName]"
    />
  </div>
</template>

<script setup lang="ts">

const props = defineProps<{
  label: string;
  value: string;
  onChange?: (event: Event) => void;
  onInput?: (event: Event) => void;
  disabled?: boolean;
  placeholder?: string;
  rightLabel?: string | (() => string);
  type?: 'text' | 'number' | 'email' | 'password';
  className?: string;
  inputClassName?: string;
  labelClassName?: string;
}>();

const emit = defineEmits<{
  (e: 'update:value', value: string): void;
}>();

const handleInput = (event: Event) => {
  const inputElement = event.target as HTMLInputElement;
  if (props.onInput) {
    props.onInput(event);
  }

  emit('update:value', inputElement.value);
};
</script>
