// examples/react-ui/src/components/FormSelect/FormSelect.tsx
import React from 'react';

interface FormSelectProps {
  label: string;
  value: string;
  onChange: (event: React.ChangeEvent<HTMLSelectElement>) => void;
  options: Array<{ value: string; label: string }>;
  disabled?: boolean;
  className?: string;
  selectClassName?: string;
  labelClassName?: string;
}

export const FormSelect: React.FC<FormSelectProps> = ({ label, value, onChange, options, disabled = false, className = '', selectClassName = '', labelClassName = '', }) => {
  return (
    <div className={`form-field ${className}`}>
      <label className={`form-label ${labelClassName}`}>
        {label}
      </label>
      <select
        value={value}
        onChange={onChange}
        disabled={disabled}
        className={`form-select ${selectClassName}`}
      >
        <option value="" disabled>Select {label}</option>
        {options.map((option, index) => (
          <option key={index} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
};

// examples/vue-ui/src/components/FormSelect.vue
<template>
  <div :class="['form-field', className]">
    <label :class="['form-label', labelClassName]">
      {{ label }}
    </label>
    <select
      v-model="selectedValue"
      @change="handleChange"
      :placeholder="placeholder"
      :disabled="disabled"
      :class="['form-select', selectClassName]"
    >
      <option value="" disabled>Select {{ label }}</option>
      <option v-for="(option, index) in options" :key="index" :value="option.value">
        {{ option.label }}
      </option>
    </select>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const props = defineProps<{
  label: string;
  value: string;
  options: { value: string; label: string }[];
  disabled?: boolean;
  className?: string;
  selectClassName?: string;
  labelClassName?: string;
  placeholder?: string;
}>();

const emit = defineEmits<{
  (e: 'updateValue', value: string): void;
}>();

const selectedValue = ref<string>(props.value);

const handleChange = () => {
  emit('updateValue', selectedValue.value);
};
</script>
